### ISSUE TITLE
Error after make

### ISSUE THREAD

**Issue by iw2gob** [on7lds/NextionDriver#1]
Hi,
I would like to install new modem driver, but  after make I have this errors:

rm -f NextionDriver *.o *.d *.bak *~
gcc NextionDriver.c basicFunctions.c processCommands.c processButtons.c helpers.c -Wall -O2 -D_GNU_SOURCE -o NextionDriver
helpers.c: In function â€˜readConfigâ€™:
helpers.c:162:10: error: redeclaration of â€˜iâ€™ with no linkage
  for(int i=0; i<14; i++) modeIsEnabled[i]=0;
          ^
helpers.c:154:9: note: previous declaration of â€˜iâ€™ was here
     int i,found,ok;
         ^
helpers.c:162:2: error: â€˜forâ€™ loop initial declarations are only allowed in C99 or C11 mode
  for(int i=0; i<14; i++) modeIsEnabled[i]=0;
  ^
helpers.c:162:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
Makefile:12: set di istruzioni per l'obiettivo "NextionDriver" non riuscito
make: *** [NextionDriver] Errore 1

Can you help me ?

73, Maurizio IW2GOB

**Comment by iw2gob** [comment]
I think I found the problem:

I have corrected the line:
for (int i = 0; i <14; i ++) modeIsEnabled [i] = 0;
in
for (i = 0; i <14; i ++) modeIsEnabled [i] = 0;

Now I can  compile correctly

73, Maurizio IW2GOB

**Comment by on7lds** [comment]
Sorry for my late reply.
it was a C99 declaration. The makefile now is changed to compile it correctly.
(or, ofcourse, you could rephrase th e declaration like you did.)
