### ISSUE TITLE
Nextion Driver stops D-Star Network

### ISSUE THREAD

**Issue by ZL1CTS** [on7lds/NextionDriver#10]
Hi All
I have an issue with the nextion drivers on RPI and zum-radio.
with the driver installed, after a random amount of time, in pi-star, the dstar network status goes red and dstar network in no longer available, the only solution is to reboot.

I have tried all current versions of pi-star, different SD cards and different Pi's and PSU, all the same results. in pi-star the port changes from modem to /dev/tty/NextionDriver once drivers are installed, screen works great with enhanced items showing up, but it kills my dstar network, DMR and YSF carry on as normal.... very frustrating,

I am currently testing with a usb to ttl adaptor to see if it is an issue when passing through the zum-radio board out of the built in connectors

anyone have an idea what it could be or where I can look to see whats going on?
thanks
Cliff

**Comment by ZL1CTS** [comment]
OK An update, with a usb to ttl converter, after installing the nextion driver to the pi the d-star network stops communicating after an hour or so of being idle.
currently re imaged sd card and running without driver and all is well.. something odd somewhere
love to get this fixed, cant be the only one with the issue can i?

thanks

Cliff

**Comment by on7lds** [comment]
When the problem starts, try to check the logs to see if there are any hints about what happened.
At least check the mmdvmhost log and syslog

**Comment by ZL1CTS** [comment]
Hi, OK I have just put in the card I have setup which includes the drivers, when it stops, I'll have a look and see, not sure what I am looking for, but hopefully something may stand out
thanks
Cliff

**Comment by ZL1CTS** [comment]
RIght it just failed and this is in the syslog, I forgot to get the MMDVM log so hav to wait for it to fail again as I rebooted... looks like there are errors in syslog as below
Feb  2 11:45:29 pi-star NextionDriver:  NET: t22.txt="0.19"
Feb  2 11:45:29 pi-star NextionDriver:   LH: check [t22.txt="0.19"] on page 0
Feb  2 11:45:29 pi-star NextionDriver:   LH: page 0 field 22 is [txt="0.19"]
Feb  2 11:45:29 pi-star NextionDriver:   LH: statusval 24
Feb  2 11:45:29 pi-star NextionDriver: LH Inhibit#012 
Feb  2 11:45:29 pi-star NextionDriver:  NET: cpuload.val=19
Feb  2 11:45:29 pi-star NextionDriver:   LH: check [cpuload.val=19] on page 0
Feb  2 11:45:29 pi-star NextionDriver:  NET: t23.txt="84"
Feb  2 11:45:29 pi-star NextionDriver:   LH: check [t23.txt="84"] on page 0
Feb  2 11:45:29 pi-star NextionDriver:   LH: page 0 field 23 is [txt="84"]
Feb  2 11:45:29 pi-star NextionDriver:   LH: statusval 24
Feb  2 11:45:29 pi-star NextionDriver: LH Inhibit#012 
Feb  2 11:45:29 pi-star NextionDriver:  NET: MMDVM.status.val=24
Feb  2 11:45:29 pi-star NextionDriver:   LH: check [MMDVM.status.val=24] on page 0
Feb  2 11:45:29 pi-star NextionDriver:  NET: click S0,1
Feb  2 11:45:29 pi-star NextionDriver:   LH: check [click S0,1] on page 0
Feb  2 11:45:29 pi-star NextionDriver:  NET: t2.txt="02/02/20 11:45:29"
Feb  2 11:45:29 pi-star NextionDriver:   LH: check [t2.txt="02/02/20 11:45:29"] on page 0
Feb  2 11:45:29 pi-star NextionDriver:   LH: page 0 field 2 is [txt="02/02/20 11:45:29"]
Feb  2 11:45:29 pi-star NextionDriver:   LH: statusval 24
Feb  2 11:45:29 pi-star NextionDriver: LH Inhibit#012 
Feb  2 11:45:29 pi-star rsyslogd: file '10' write error: No space left on device [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Feb  2 11:45:29 pi-star rsyslogd: action 'action-13-builtin:omfile' (module 'builtin:omfile') message lost, could not be processed. Check for additional error messages before this one. [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Feb  2 11:45:29 pi-star rsyslogd: file '10' write error: No space left on device [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Feb  2 11:45:29 pi-star rsyslogd: action 'action-13-builtin:omfile' (module 'builtin:omfile') message lost, could not be processed. Check for additional error messages before this one. [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Feb  2 11:45:29 pi-star rsyslogd: file '10' write error: No space left on device [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Feb  2 11:45:29 pi-star rsyslogd: action 'action-13-builtin:omfile' (module 'builtin:omfile') message lost, could not be processed. Check for additional error messages before this one. [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Feb  2 11:45:29 pi-star rsyslogd: file '10' write error: No space left on device [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Feb  2 11:45:29 pi-star rsyslogd: action 'action-13-builtin:omfile' (module 'builtin:omfile') message lost, could not be processed. Check for additional error messages before this one. [v8.1

I'll add the mmdvm as an when it next fails, not sure what the no space left on device means?  
[syslog.txt](https://github.com/on7lds/NextionDriver/files/4143347/syslog.txt)

**Comment by ZL1CTS** [comment]
do worry appearently it the log level
