### ISSUE TITLE
Screen Inhibit to ignore request for data, Process All Request Regardless of Inhibit Status

### ISSUE THREAD

**Issue by VE3RD** [on7lds/NextionDriver#11]
Would it be possible to limit only the screen changes with the inhibit command from the screen, and process any data requests regardless of the inhibit status. Possibly a new command to handle just the screen changes to provide this option to the users
I find myself chewing up a lot of real estate with the the turn on/off the inhibit and losing track of whether it is on or off. This switch does not seem to be reliable as I turn off the inhibit, switch to another screen, but it does not process the data request by the opening screen. All I need it to do is stop it from automatically changing screens while I am getting or setting parameters.

**Comment by on7lds** [comment]
If you just want to block just the screen change commands, you could rename the screens (so the change screen command has no effect) and monitor the status codes (in the Nextion) and act upon.
Then do not change screens when on your settings page, but do so on other pages.
