### ISSUE TITLE
tg2bis and locale

### ISSUE THREAD

**Issue by sm7tix** [on7lds/NextionDriver#12]
When i use locale sv_SE-UTF8 in pi-star the time in tg2bis missing the last digit in seconds. Changing the size of the field it populate doesnt matter but if i set en_GB utf8 it fits all the numbers. I am not a programmer but i hope i described it so you understand. Perhaps the tg2bis varialbe is to small?
![received_317129009592429](https://user-images.githubusercontent.com/11734103/93430848-91ffe800-f8c3-11ea-87fc-b07d5f114e04.jpeg)

**Comment by on7lds** [comment]
I will configure a setup like yours to test it.
* Which Pi-Star version ?
* Which HMI file (could you send me the hmi file you are using)

**Comment by sm7tix** [comment]
I use the latest version 4.1.2. I attach the HMI but it is not me that made it. It is Perry WB7NIL
[NX8048K070_V5_Model 3_A_7inch-(WB7NIL)SINGLE_L3-DMR_ON7LDS.zip](https://github.com/on7lds/NextionDriver/files/5260157/NX8048K070_V5_Model.3_A_7inch-.WB7NIL.SINGLE_L3-DMR_ON7LDS.zip)

 that helped me build a readable one becasue i am a little visually impaired.

**Comment by on7lds** [comment]
It has to be changed in the screen definition (with the Nextion Editor).

Standard Pi-Star dates are like 'Wed May 20 20:25:48 CEST 2020'
In the Touch Release event of the button 'MMDVM restart', the four first characters are omitted to drop the weekday name and then the following 16 characters are taken:
**substr t2.txt,localdate.txt,4,16//Take out the Day of the week for the new time**

This makes from 'Wed **May 20 20:25:48** CEST 2020' --> 'May 20 20:25:48 '

But the sv_SE locale shows the date as 'ons **20 maj 2020 20:2**5:48 CEST' which is then changed to '20 maj 2020 20:2' and this is what you see on your screen.

So you have to change that line in yout .HMI file to
substr t2.txt,localdate.txt,4,**17**
which should  show **20 maj 2020 20:25** or
substr t2.txt,localdate.txt,4,**20**
which should show **maj 2020 20:5:48**
and then reload it to your screen.
(I cannot test it, the biggest screen I have is only 4.3")

**Comment by sm7tix** [comment]
Ok.
I am not so familiar with the editor, bur try to find it.
73 de Sm7tix
Med vänlig hälsning

Stefan Rydberg
0767-882514

Den 22 september 2020 12:51:36 skrev on7lds <notifications@github.com>:

**Comment by sm7tix** [comment]
I let Perry edit the file and try it, but same result. 

---
Med vänlig hälsning

Stefan Rydberg
0767-882514 

2020-09-22 12:50 skrev on7lds:

> It has to be changed in the screen definition (with the Nextion Editor). 
> 
> Standard Pi-Star dates are like 'Wed May 20 20:25:48 CEST 2020'
> In the Touch Release event of the button 'MMDVM restart', the four first characters are omitted to drop the weekday name and then the following 16 characters are taken:
> SUBSTR T2.TXT,LOCALDATE.TXT,4,16//TAKE OUT THE DAY OF THE WEEK FOR THE NEW TIME 
> 
> This makes from 'Wed MAY 20 20:25:48 CEST 2020' --> 'May 20 20:25:48 ' 
> 
> But the sv_SE locale shows the date as 'ons 20 MAJ 2020 20:25:48 CEST' which is then changed to '20 maj 2020 20:2' and this is what you see on your screen. 
> 
> So you have to change that line in yout .HMI file to
> substr t2.txt,localdate.txt,4,17
> which should show 20 MAJ 2020 20:25 or
> substr t2.txt,localdate.txt,4,20
> which should show MAJ 2020 20:5:48
> and then reload it to your screen.
> (I cannot test it, the biggest screen I have is only 4.3") 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/on7lds/NextionDriver/issues/12#issuecomment-696646081
[2]

**Comment by on7lds** [comment]
Did he replace *all* occurences of SUBSTR T2.TXT,LOCALDATE.TXT,4,16 ?
I tried to find them and changed it. As said, I cannot test it. HMI & TFT attached.
If it still does not shows the full date/time, let met know where exactly (which page) and what you did to get there.

[NX8048K070_V5_Model.3_A_7inch-.WB7NIL.SINGLE_L3-DMR_ON7LDS_SV.zip](https://github.com/on7lds/NextionDriver/files/5287881/NX8048K070_V5_Model.3_A_7inch-.WB7NIL.SINGLE_L3-DMR_ON7LDS_SV.zip)

**Comment by sm7tix** [comment]
Looks like it works now.
Med vänlig hälsning

Stefan Rydberg
0767-882514

Den 27 september 2020 09:32:03 skrev on7lds <notifications@github.com>:

**Comment by on7lds** [comment]
Glad it works.

**Comment by TOZSOCS** [comment]
I want to set the "TOR" format but I can't find the line "substr t2.txt, localdate.txt, 4.16" in the .HMI file.
