### ISSUE TITLE
I suggest not to set "WaitForLan=1" as default value, very unfriendly experience 

### ISSUE THREAD

**Issue by bi7jta** [on7lds/NextionDriver#15]
Hi ON7LDS,
I suggest not to set "WaitForLan=1" as default value, very unfriendly experience , many new users need a Wi-Fi AP prompt, instead of "Waiting  for network".

Just a suggestion

[NextionDriver]
Port=modem
DataFilesPath=/usr/local/etc/
LogLevel=2
GroupsFile=groups.txt
DMRidFile=stripped.csv
#DMRidDelimiter=,
#DMRidId=1
#DMRidCall=2
#DMRidName=3
#DMRidX1=4
#DMRidX2=5
#DMRidX3=7
ShowModeStatus=0
RemoveDim=0
WaitForLan=1
SleepWhenInactive=0

DE BI7JTA

**Comment by on7lds** [comment]
will be taken in account in the next NextionDriver Installer
(soon te be released now)
