### ISSUE TITLE
Updates to groups.txt and stripped.csv files?

### ISSUE THREAD

**Issue by rd0fun** [on7lds/NextionDriver#16]
Just looking for some help.  How does one keep groups.txt and stripped.csv up to date? Does that happen automatically?

Thanks

**Comment by rd0fun** [comment]
Answered my own question, partially.

/usr/local/etc/stripped.csv can be updated directly from RadioID.net like this

sudo rm -f /usr/local/etc/stripped.csv
sudo wget -O /usr/local/etc/stripped.csv https://database.radioid.net/static/user.csv

However, my Callsign is not in that file, as confirmed with grep, but still my hotspot says "<callsign> not in stripped.csv"

Does this updated have to be loaded into memory by something? Is it used to update some database?
How exactly does NextionDriver use this .csv file?

Thank you.

**Comment by on7lds** [comment]
NextionDriver read these files (groups and users) when starting.
If you pull a new users file (f.e. stripped.csv), you have to restart NextionDriver.

As of V1.19 you can send the signal SIGUSR1 to NextionDriver which will reread the users and groups file.
So after gettting the new csv file(s), you could do
`kill -SIGUSR1  $(pidof NextionDriver)`

**Comment by rd0fun** [comment]
Thank you for the reply. I have updated to this release.

What I did not realize (duh) is that the groupt.txt is BM specific.

Would be really nice to see pi-star become Newtwork Agnostic at some point, and be able to manage multiple group and talker aliases from multiple networks.

Thank you for the fantastic software!
