### ISSUE TITLE
Troubleshooting assistance

### ISSUE THREAD

**Issue by hammyMarc** [on7lds/NextionDriver#20]
Build: Pi 3b+, MMDVM Jumbospot, pimoroni fam shim w/ pimoroni software installed. Soldered pins to the modem holes labeled Nextion, wired accordingly. In Pi-Star, set the display type to Nextion, Port to Modem and chose the Layout of ON7LDS HS. The display powers-up, but no data is displayed.

To eliminate the possibility of a bad display, I have succeeded in connecting the display via FT232RL / USB. Works great.

Some other troubleshooting steps included:
1) power cycling.
2) switching between Wait on LAN 1 to 0, then back.
3) switching the layout to the low-speed option.

I'm fresh out of ideas and really need some help, please.

**Comment by hammyMarc** [comment]
![IMG_4793](https://user-images.githubusercontent.com/45080422/120080159-94872400-c085-11eb-8d34-5e7500ce67dd.jpg)
<img width="1028" alt="Screenshot 2021-05-29 135011" src="https://user-images.githubusercontent.com/45080422/120080177-9ea92280-c085-11eb-9f45-df91ac901cda.png">

**Comment by hammyMarc** [comment]
Nevermind, all. I've decided to solder a FT232RL to the Pi and move on.

**Comment by on7lds** [comment]
Modem connected displays will not work in HS layout. The communication speed modem<-->display is programmed in the modem and is, as far as I know, always 9600baud.
In any case, you have more flexibility with an USB-RS232 solution. Not only to use the higher communication speed but then you can also use buttons on the Nextion to start some actions on the Pi.

**Comment by hammyMarc** [comment]
Thank you friend. 73!
