### ISSUE TITLE
Users size limit reached - Consider increasing users table size

### ISSUE THREAD

**Issue by KB4MDD** [on7lds/NextionDriver#21]
The users table is presently capped at 200,000.  Please consider increasing the size to 250,000.  At the present time the users.csv file has over 203,000 entries.

Aug 30 10:05:56 pi-star NextionDriver:   Maximum of 200000 users reached. Not adding more users.

**Comment by on7lds** [comment]
OK, is changed to 250000.
Note that the NextionDriver version number has not changed.

**Comment by on7lds** [comment]
I changed version to 1.22 to make upgrades more easy
