### ISSUE TITLE
DMRidName Options

### ISSUE THREAD

**Issue by VE3RD** [on7lds/NextionDriver#23]
The user option in mmdvmhost  indicated by earlier comments makes sense
DMRidName=3
or 
DMRidName=34

Please don't hard code this into one field. 
helpers.c
    //userDBName=34;  // fields 2 and 3
modified to
    userDBName=3;  // fields 2
Screen real estate for a full name is difficult to achieve especially on a 2.4

**Comment by KE7FNS** [comment]
> Please don't hard code this into one field.

It is **NOT** hardcoded to 34, it is initialized to fields 3 and 4 as a default.  

It is fully customizable and up to the user to customize the fields that are displayed to their own liking, or to the individual database they choose to use.

If you only want to see a first name only, then set the configuration to only one field.  Or go into your database and blank out everyones last name.  

Problem solved.
