### ISSUE TITLE
Population t18-t22 still not working

### ISSUE THREAD

**Issue by VE3RD** [on7lds/NextionDriver#24]

**Comment by VE3RD** [comment]
Still Not Working for P25
   LH: check [click S0,1] on page 4
Feb  7 12:50:23 pi-star4 NextionDriver: RX:   dim=99
Feb  7 12:50:23 pi-star4 NextionDriver: RX:   t0.txt="N VE3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:  TX:  t0.txt="N VE3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:  NET: t0.txt="N VE3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: check [t0.txt="N VE3RD"] on page 4
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: page 4 field 0 is [txt="N VE3RD"]
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: statusval 5
Feb  7 12:50:23 pi-star4 NextionDriver: LH Inhibit#012
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 212946 [[KC2UOW] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 106473 [KF7EJB] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 53236 [HB9BBM] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 26618 [DK7DN] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 13309 [BG9FMC] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 6654 [AB6XS] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (0 [] - 3327 [5V1JE] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (1663 [2E0WSP] - 3327 [5V1JE] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (1663 [2E0WSP] - 2495 [4G1BID] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2079 [2M0JST] - 2495 [4G1BID] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2287 [2W0RGL] - 2495 [4G1BID] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2287 [2W0RGL] - 2391 [4F1NKS] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2339 [2W1GLY] - 2391 [4F1NKS] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2339 [2W1GLY] - 2365 [4D1Z] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2352 [3B8GW] - 2365 [4D1Z] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2352 [3B8GW] - 2358 [3Z4S] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2352 [3B8GW] - 2355 [3Z1P] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2353 [3DA0MF] - 2355 [3Z1P] )
Feb  7 12:50:23 pi-star4 NextionDriver: --- User index search for call 3RD (2353 [3DA0MF] - 2354 [3X2021] )
Feb  7 12:50:23 pi-star4 NextionDriver:  TX:  t18.txt="DMRID 3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:  NET: t18.txt="DMRID 3RD"
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: check [t18.txt="DMRID 3RD"] on page 4
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: page 4 field 18 is [txt="DMRID 3RD"]
Feb  7 12:50:23 pi-star4 NextionDriver:   LH: statusval 5
Feb  7 12:50:23 pi-star4 NextionDriver: LH Inhibit#012
Feb  7 12:50:23 pi-star4 NextionDriver:  TX:  t19.txt="Not found in"
Feb  7 12:50:24 pi-star4 NextionDriver:  NET: t19.txt="Not found in"

I revised ver 1.24 as follows and had it working  &TXbuffer[12] does not work for non DMR modes
I added a filter on the TS1,P25,YSF etc blocks such that it would ignore DMR all together
and changed all the [&TXbuffer[12] to &TXbuffer[10]

I then duplicated the TS2 block and converted it to TS1

not sure if I broke anything else, but everything I needed was working fine
I
I wrote a script that returns the info string as follows,
/home/pi-star/Scripts/getuserinfo.sh K4WZV
Robert|Springhill|Florida|United States
This functions in all modes, so will be using this until the driver is repaired

**Comment by VE3RD** [comment]
I Revised ver1.25 same as I did with the  1.24 and the following tested ok
P25, YSF, and DMR TS2. I have no way to test the TS!,and don't use it anyway.

**Comment by on7lds** [comment]
OK, 
in any case I am reviewing the whole lookup thing to make it work better for all modes.
