### ISSUE TITLE
Screen don't wake up

### ISSUE THREAD

**Issue by pjao** [on7lds/NextionDriver#6]
Hi there,

With the new setting SleepWhenInactive set, after the idle time, screen goes off, then even with traffic coming from RF or NET screen don't wake up, just if I touch on it.

Is it suppose to behave like that?

Thanks
Paulo - CT2JAY

**Comment by on7lds** [comment]
It should wake up on touch or on any page change. 
What is your SleepWhenInactive value ?

When the value is relatively low (let's say: some minutes) and the talker talks longer than that, the screen goes to sleep and only awakens on page change (that is: after _the whole_ QSO).
Therefore, I have it here at 600 seconds for the moment.
I am still tuning this behavior, I'm thinking about a method to awaken it when the QSO is stil active.

The main goal is to signal the death of MMDVMHost and then spare the screen (mainly the backlight) when there is nothing to show any more.

**Comment by pjao** [comment]
I know understand your idea!

SleepWhenInactive was too low, with 60 seconds. 
It must be greater  than the value defined in RFModeHang, NetModeHang or ModeHang. This way it behaves like it should. 
I'm keeping testing it, with good results configured with 600 seconds.
